/* Generated automatically by the program `genconstants'
   from the machine description file `md'.  */

#ifndef GCC_INSN_CONSTANTS_H
#define GCC_INSN_CONSTANTS_H

#define UNSPECV_LDSTUB 10
#define UNSPEC_MUL8UL 46
#define UNSPEC_MULDUL 47
#define UNSPEC_TLSLDO 32
#define UNSPECV_GOTO 2
#define UNSPEC_SETM44 7
#define UNSPECV_CAS 8
#define UNSPECV_FLUSH 4
#define UNSPEC_TLSLDM 31
#define UNSPEC_EMB_SETHM 18
#define UNSPEC_MOVE_PIC_LABEL 5
#define UNSPEC_TLSLE 34
#define UNSPEC_SP_TEST 61
#define UNSPEC_EMB_HISUM 11
#define UNSPECV_FLUSHW 1
#define UNSPEC_FPACK16 40
#define UNSPECV_PROBE_STACK_RANGE 11
#define UNSPEC_PDIST 50
#define UNSPEC_SETH44 6
#define UNSPECV_SAVEW 6
#define UNSPEC_MOVE_GOTDATA 19
#define UNSPEC_EMB_TEXTULO 15
#define UNSPEC_FPACK32 41
#define UNSPEC_LOAD_PCREL_SYM 2
#define UNSPEC_FPMERGE 44
#define UNSPEC_UPDATE_RETURN 1
#define UNSPEC_FEXPAND 43
#define UNSPEC_MEMBAR 20
#define UNSPECV_BLOCKAGE 0
#define UNSPECV_SETJMP 5
#define UNSPEC_SP_SET 60
#define UNSPEC_FPACKFIX 42
#define UNSPEC_ALIGNADDR 49
#define UNSPECV_SWAP 9
#define UNSPEC_TLSGD 30
#define UNSPEC_TLSLD_BASE 35
#define UNSPEC_MOVE_PIC 0
#define UNSPEC_EMB_TEXTHI 14
#define UNSPEC_ALIGNDATA 48
#define UNSPEC_SETHH 9
#define UNSPEC_SETLM 10
#define UNSPEC_TLSIE 33
#define UNSPEC_EMB_TEXTUHI 13
#define UNSPEC_MUL16AL 45

#endif /* GCC_INSN_CONSTANTS_H */
